// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5UeXbAdlpsi00aL17-KshONdlyefSOI',
    appId: '1:306696848709:web:e7fa28954a245c23e76a2c',
    messagingSenderId: '306696848709',
    projectId: 'final-project-rent-motos',
    authDomain: 'final-project-rent-motos.firebaseapp.com',
    storageBucket: 'final-project-rent-motos.appspot.com',
    measurementId: 'G-RL2VK90T72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5M96eLip2AWIkyBL6bHDPfEWkefKks4A',
    appId: '1:306696848709:android:19917a03ac43356ce76a2c',
    messagingSenderId: '306696848709',
    projectId: 'final-project-rent-motos',
    storageBucket: 'final-project-rent-motos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQJc2DZKFcusI7f3GqfbOxv8kzHDpxOfQ',
    appId: '1:306696848709:ios:12a947b5fd6041c8e76a2c',
    messagingSenderId: '306696848709',
    projectId: 'final-project-rent-motos',
    storageBucket: 'final-project-rent-motos.appspot.com',
    iosBundleId: 'com.example.flutterRentMoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQJc2DZKFcusI7f3GqfbOxv8kzHDpxOfQ',
    appId: '1:306696848709:ios:12a947b5fd6041c8e76a2c',
    messagingSenderId: '306696848709',
    projectId: 'final-project-rent-motos',
    storageBucket: 'final-project-rent-motos.appspot.com',
    iosBundleId: 'com.example.flutterRentMoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL5UeXbAdlpsi00aL17-KshONdlyefSOI',
    appId: '1:306696848709:web:1fbba4b1ff0c533fe76a2c',
    messagingSenderId: '306696848709',
    projectId: 'final-project-rent-motos',
    authDomain: 'final-project-rent-motos.firebaseapp.com',
    storageBucket: 'final-project-rent-motos.appspot.com',
    measurementId: 'G-NT1RYJ98K8',
  );
}
